export const TEXTS = {
    lv: {
        madeBy: "Veidoja Valters Hūns",
        home: "Sākums",
        road: "Ceļš",
        liepaja: "Liepāja",
        grobina: "Grobiņa",
        saldus: "Saldus",
        riga: "Rīga",
        tram: "Tramvajs",
        library: "Bibliotēka",
        university: "Universitāte",
        grobinaTitle: "GROBIŅA",
        saldusTitle: "SALDUS",
        rigaTitle: "RĪGA",
        tramTitle: "TRAMVAJS",
        libraryTitle: "BIBLIOTĒKA",
        uniTitle: "UNIVERSITĀTE",
        altMap: "Latvijas karte",
        altPortrait: "Autora portrets",
        altBeach: "Liepājas pludmale",
        altGrobina: "Grobiņas vēja ģeneratori",
        altSaldus: "Saldus aplis",
        altRiga: "Rīgas iebraukšanas zīme",
        altTram: "Rīga 1. tramvajs",
        altLibrary: "Latvijas Nacionālā Bibliotēka",
        altUni: "Latvijas Universitātes galvenā ēka",
        mansCels: "Mans ceļš uz Latvijas Universitāti",
        halfWay: "Pusceļš",
        destination: "Galamērķis sasniegts",
        aboutWebsiteTitle: "Par šo mājaslapu",
        aboutMyselfTitle: "Par mani",
        grobinaTextTitle: "Vēljoprojām tuvu mājām",
        biblTextTitle: "Pēdējais posms",
        driveStart: "Ceļa sākums - Liepāja",
        closerDestination: "Tuvāk galapunktam",
        everydayTransport: "Ikdienas transports",
        aboutText: "Hey! Esmu šīs lapas autors - Valters Hūns, 3. kursa students Latvijas Universitātes Datorzinātņu fakultāte. Lapa veidota kursam Tīmekļa Dizaini I.",
        latviaText1: "Šī mājaslapa apraksta manu ceļu no Liepājas līdz Latvijas Universitātei, iekļaujot septiņas vietas un citus objektus, kurus iespējams redzēt tajā. Šajā ceļā ir iekļauta Liepājas pludmale, kur sākas mans ceļš un ved cauri Grobiņas vēja parkam, kas ir diezgan unikāla vieta visā Latvijā. Tālāk tiek braukts cauri Saldus aplis, kur var nedaudz atpūsties. Svarīgs posms - iebraukšana Rīgā un tās robežzīme. Nonākot Rīgā savu ceļu turpinu ar tramvaju, precīzāk 1. tramvaju. Pa ceļam uz universitāte braucu garām Latvijas Nacionālajai Bibliotēkai, ēkai, kuru bieži apmeklēju, lai mierīgi varētu mācīties. Līdz beigās sasniedzu savu galamērķi - Latvijas Universitātes ēku Raiņa bulvārī 18.",
        latviaText2: "Kopumā ceļš ir vairāk nekā 200 km garš un diezgan nogurdinošs, ar šīm izvēlētajām vietām garo ceļu var sadalīt īsākos posmos un nevis gaidīt pašu galamērķi, bet pieturpunktus. Katram izvēlētajam objektam ir kaut kāda nozīme vai asociācija, kura tiks parādīta ar ilustrācijām un to paskaidrojošajiem tekstiem. Visas ilustrācijas veidotas ar programmu Adobe Illustrator. Vietne izvietota pakalpojumā ",
        liepajaText1: "Liepāja, pilsēta no kuras es nāku, ir gleznaina vieta, kas ietver jūru un skaisto pludmali. Šī pilsēta, kas atrodas Latvijas piekrastē, ir bagāta ar vēsturi, kultūru un dabas skaistumu. Liepājas jūra un pludmale ir vieni no tās lielākajiem un skaistākajiem piesaistes punktiem. Un arī es vienmēr gaidu brīvdienas, kad varēšu aizbraukt mājās un doties pastaigā gar jūru. Manuprāt nekas nav labāks par vēju un svaigo jūras gaisu, ko tas atnes. Bet diemžēl, ņemot vērā attālumu no Rīgas, ne vienmēr sanāk aizbraukt mājās.", 
        liepajaText2: " Un man ceļš uz Latvijas Universitāti sākas tieši šeit, jo Liepājā rīkoto IT pasākumu dēļ es atradu savu interesi par programmēšanu un datorzinātnēm, kas arī noveda mani līdz lēmumam studēt datorzinātnes Latvijas Universitātē, kur tad es arī šobrīd mācos. Pēc studiju pabeigšanas labprāt atgrieztos Liepājā un turpinātu savu IT karjeru tur. ",
        grobinaText1: "Turpinot ceļu uz Latvijas Universitāti, ceļš ved garām Grobiņas vēja ģeneratoru parkam. Šī vieta man šķiet ļoti interesanta un vienmēr paliek atmiņā. Tā gan vairāk asociējas ar ceļu mājup no Rīgas. Ieraugot vēja ģeneratorus tālumā, tie simbolizē veikto ceļu un sniedz pazīmi, ka tuvojos mājām. Varbūt arī tāpēc, ka citur Latvijā šādu vēja parku īsti nav un ieraugot tos nāk prātā tikai Grobiņa. Arī pašā Grobiņā esmu pavadījis daudz laiku, esmu tur mācījies un vienmēr ir priekš tai braukt cauri vai piestāt.",
        grobinaText2: "Ilustrācijā, kas ir izveidota, ir attēloti šie vēja ģeneratori. Tā kā turpmākais ceļš no šīs vietas ir ļoti tāls, ilustrācijā tas ir attēlots kā ceļš, kas šķiet nesbeidzams un nebeidzas redzamajā telpā. Tas rada sajūtu, ka priekšā ir garš un nepazīstams ceļš, kas vēl jāiziet. Aptuveni jāmēro vēl 200km, varbūt priekš kāda tas nav nekas, bet bieži braucot šis ceļš kļūst garlaicīgs un ļoti nogurdinošs, it īpaši, ja nav vēlme braukt uz Rīgu.",        
        saldusText1: "Braucot no Liepājas uz Rīgu, aptuveni pusceļā ir pilsēta Saldus, kur ir jāizbrauc cauri aplim. Kaut arī šajā konkrētajā vietā nav īpaši izcilu objektu vai ievērojamu vietu, kas pievilinātu uzmanību, Saldus kā viduspunkts nodrošina svarīgu funkciju ceļotājiem. Tas vizuāli sadala garo ceļu divās daļās un sniedz atskaites punktu, kas liecina par veikto ceļa posmu progresu. Tas arī norāda, ka pirms Saldus nav tik būtisku vietu vai objektu, kas vērā ņemami atspoguļotu ceļotāju ceļojuma attīstību. Bieži vien šeit apstājos, lai atpūstos, uzpildītu degvielu vai paēstu. No šīs vietas šķiet, ka gan turpceļš, gan atpakaļ ceļš rit daudz ātrāk, tu esi tuvāk savam galamērķim un ir lielāka motivācija to ātrāk sasniegt. ",
        saldusText2: "Ilustrācijā ir attēlots apļveida ceļš, kas ienāk un iziet no visām pusēm, tādējādi vizuāli parādot ceļa viduspunktu. Lai papildinātu to, ir pievienotas skaidri redzamas ceļa zīmes, kas norāda uz dažādiem virzieniem, kā arī ir iezīmēts konkrēts maršruts, kas savieno ceļa daļas. Arī realitātē šis aplis ir ļoti līdzīgs.",
        rigaText: "Kā vēlviena no svarīgām norādēm, kas simbolizē veikto ceļu ir Rīgas robežzīme, kas norāda uz to, ka esmu nokļuvis Rīgā - Latvijas galvaspilsētā. Bet es vēl neesmu sasniedzis savu galamērķi - Latvijas Universitāti. Ar šo vietu man asociējas arī lidosta un lidmašīnas, jo netālu no ceļa ir Rīgas lidosta un braucot bieži var vērot, kā pāri lido lidmašīnas, manuprāt diezgan interesanti.  ",
        rigaText2: "Pēc tik gara ceļa beidzot ir sasniegta galvaspilsēta. Ir sajūta, ka jau esmu galā, tomēr vēl palicis ilgais ceļš cauri Rīgai. Stāvēšana sastrēgumos, nebeidzamie ceļu darbi, nekārtība. Vēl kāda no pazīmēm, ka esmu nonācis Rīgā ir bedres, kuras nav sastaptas visā garajā ceļā. Personīgi man ļoti nepatīk braukt cauri Rīgai, jo tur valda pilnīga nekārtība, tāda kādu neesmu sastapis citviet. Tādēļ arī izvēlos Liepāju pār Rīgu, jo tur valda daudz mierīgāka atmosfēra, tur šķiet daudz mājīgāk, pazīstamāk. Tomēr izglītība ir jāiegūst un Rīgā ir labākās augstskolas Latvijā, tādēļ nekas cits īsti neatliek, kā tikai to visu paciest.",
        tramvajsText: "Ikdienā nepieciešams nokļūt no manas dzīvesvietas Rīgā līdz Latvijas Universitātei, kas atrodas pašā centrā. Tā kā pārvietoties ar savu personīgo automašīnu nav visai izdevīgi un ērti, tad otrā izvēle ir sabiedriskais transports. Man visērtākais sabiedriskais transports ir tramvajs, jo iekāpšanas pieturvieta ir pietiekami tuvu manai dzīvesvietai un ir iespējams ar vienu transportu nokļūt līdz pašam Rīgas centram. Viens no lielākajiem tramvaja plusiem ir, ka nav jāstāv ilgajos un garajos sastrēgumos.",
        tramvajsText2: "Un tā kā tieši šis transports ir daļa no mana ceļa līdz Latvijas Universitātei, tad šajā ilustrācijā esmu attēlojis tramvaju Rīgas tramvaja krāsās. Papildus ilustrācijā ir iekļauts tēls - students, kas esmu domāts es. Šis tēls stāv un gaida pienākam tramvaju, lai nokļūtu līdz Latvijas Universitātei. Un arī es katru dienu stāvu un gaidu tramvaju, lai nokļūtu līdz pilsētas centram.",
        libraryText1: "Ceļā uz Latvijas Universitāti atrodas vēl viens objekts, kas ir ļoti nozīmīgs kopējā ceļā uz Latvijas Universitāti - Latvijas Nacionālā Bibliotēka. Gandrīz katru dienu es braucu tai garām, un vienmēr šī vieta man asociējas ar mācīšanos un zināšanām. Bibliotēkas ēka pati par sevi ir interesanta ar savu arhitektūru un nedaudz izceļas no Rīgas pārējās ainavas.",
        libraryText2: "Bibliotēka piedāvā ne tikai bagātīgu grāmatu krājumu, bet arī dažādus resursus, kas atbalsta mācīšanos. Es pat pats laiku pa laikam apmeklēju bibliotēku, lai iegrimtu klusumā un koncentrētos uz savām mācībām. Tas ir īpaši izdevīgi man, jo sabiedriskais transports apstājas tieši pie bibliotēkas, ļaujot man ērti nokļūt no turienes līdz centram un atpakaļ. ",
        libraryText3: "Tādējādi Latvijas Nacionālā Bibliotēka man ir ne tikai nozīmīgs simbols un atbalsts mācībām, bet arī praktiska un ērta vieta, kas ir ļoti tuvu manam ceļa maršrutam.",
        uniText: "Šis garais ceļš no Liepājas uz Latvijas Universitāti sevī ietver ļoti daudz un dažādas vietas, kas ar kaut ko asociējas. Šajā ceļā mans galamērķis ir Latvijas Universitāte un to es esmu sasniedzis. Pirmos divus studiju gadus man īsti nesanāca šo ceļu veikt un apmeklēt Latvijas Universitātes ēku, jo bija noteiktas attālinātās studijas. Atsākoties klātienes mācības sanāk daudz vairāk braukāt, redzēt un apmeklēt. Laika gaitā esmu pamanījis, ka universitātes ēka nemainās ārēji, tā ir noturējusi savu spēcīgo un cienījamo izskatu, kas iemieso tradīcijas un zināšanu mantojumu. Tā ir kā vēsturiska celtne, kas stāv lepni un stipri, turpinot kalpot kā zināšanu templis jaunajām paaudzēm. Tādēļ arī izdomāju izveidot ilustrāciju ar Latvijas Universitāti un savu tēlu, kurš pēc visa šī ceļa tur ir nokļuvis.",
        uniText2: "Vēl palicis gads ko mācīties, vēlviens gads, kurā vairākas reizes mērošou jau iepriekš mēroto ceļu, redzēšu visas šīs vietas un objektus. Tāpat kā ceļš ir ilgs tā arī man šis studiju process šķiet ļoti ilgs, varbūt tādēļ, ka nejūtos, ka būtu mājās. ",
    },

    en: {
        madeBy: "Made by Valters Hūns",
        home: "Home",
        road: "Road",
        liepaja: "Liepaja",
        grobina: "Grobina",
        saldus: "Saldus",
        riga: "Riga",
        tram: "Tram",
        library: "Library",
        university: "University",
        grobinaTitle: "GROBINA",
        saldusTitle: "SALDUS",
        rigaTitle: "RIGA",
        tramTitle: "TRAM",
        libraryTitle: "LIBRARY",
        uniTitle: "UNIVERSITY",
        altMap: "Map of Latvia",
        altPortrait: "Authors portrait",
        altBeach: "Liepaja beach",
        altGrobina: "Grobina wind turbines",
        altSaldus: "Saldus roundabout",
        altRiga: "Riga entry sign",
        altTram: "Tram No.1",
        altLibrary: "National Library of Latvia",
        altUni: "Main building of University of Latvia",
        mansCels: "Road to University of Latvia",
        halfWay: "Half way",
        destination: "Destination reached",
        aboutWebsiteTitle: "About this website",
        aboutMyselfTitle: "About me",
        grobinaTextTitle: "Still close to home",
        biblTextTitle: "Final stretch",
        driveStart: "Starting point - Liepaja",
        closerDestination: "Closer to destination",
        everydayTransport: "Everyday transportation",
        aboutText: "Hey! I am the author of this page - Valters Hūns, a 3rd year student at the Faculty of Computer Science at the University of Latvia. This page was created for the course Web Design I.",
        latviaText1: "This website describes my journey from Liepāja to the University of Latvia, including seven places and other objects that can be seen there. Liepāja beach is included in this path, where my path begins and leads through the Grobiņa wind farm, which is a rather unique place in all of Latvia. Next, you drive through Saldus aplis, where you can rest a little. An important stage - entering Riga and its border sign. Arriving in Riga, I continue my journey by tram, more precisely tram 1. On the way to the university, I passed by the National Library of Latvia, a building I often visit so that I can study in peace. In the end, I reached my destination - the building of the University of Latvia at Raiņa boulevard 18",
        latviaText2: "In total, the road is more than 200 km long and quite tiring, with these selected places you can divide the long road into shorter sections and not wait for the destination itself, but for the stops. Each selected object has some meaning or association, which will be shown with illustrations and explanatory texts. All illustrations are made with Adobe Illustrator. The site is hosted on the service ",
        liepajaText1: "Liepaja, the city I come from, is a picturesque place that includes the sea and the beautiful beach. This city, located on the coast of Latvia, is rich in history, culture and natural beauty. Liepāja's sea and beach are one of the biggest and most beautiful attractions. And I also always look forward to holidays when I can go home and go for a walk by the sea. In my opinion there is nothing better than the wind and the fresh sea air it brings. But unfortunately, considering the distance from Riga, it is not always possible to go home.",
        liepajaText2: "And for me, the road to the University of Latvia begins right here, because I found my interest in programming and computer science due to the IT events organized in Liepaja, which also lead to my decision to study computer science at the University of Latvia, where I am currently studying. After finishing my studies, I would like to return to Liepāja and continue my IT career there.",
        grobinaText1: "Continuing the road to the University of Latvia, the road leads past the Grobiņa wind generator park. I find this place very interesting and always memorable. It is more associated with the way home from Riga. When you see wind turbines in the distance, they symbolize the journey you have made and give you a sign that you are getting closer to home. Maybe also because there are no such wind farms anywhere else in Latvia and only Grobiņa comes to mind when you see them. I've also spent a lot of time in Grobina itself, I've studied there and it's always nice to drive through it or stop by.",
        grobinaText2: "The illustration that has been created shows these wind generators. Since the further path from this place is very far, the illustration shows it as a path that seems endless and does not end in visible space. It creates a feeling that there is a long and unknown road ahead that still needs to be covered. Approximately 200km more to go, maybe it's nothing for some, but if you drive often this road becomes boring and very tiring, especially if you don't want to go to Riga.",
        saldusText1: "Driving from Liepāja to Riga, approximately half way is the town of Saldus, where you have to go through a circle. Although this particular location does not have any particularly outstanding features or landmarks to draw attention to, Saldus as a midpoint provides an important function for travelers. It visually divides the long road into two parts and provides a reference point that shows the progress of the completed road sections. It also indicates that before Saldus there are no such significant places or objects that significantly reflect the development of the traveler's journey. I often stop here to rest, refuel or eat. From this place, it seems that both the way there and the way back go much faster, you are closer to your destination and you have more motivation to reach it faster.",
        saldusText2: "The illustration shows a circular path entering and exiting from all sides, thus visually showing the midpoint of the path. To complement this, clearly visible road signs have been added to indicate different directions, and a specific route has been marked connecting the sections of the road. This circle is also very similar in reality.",
        rigaText: "Another important sign that symbolizes the journey is the Riga border sign, which indicates that I have arrived in Riga - the capital of Latvia. But I have not yet reached my destination - the University of Latvia. I also associate the airport and airplanes with this place, because the Riga airport is close to the road and you can often watch airplanes fly over while driving, which I think is quite interesting.",
        rigaText2: "After such a long journey, the capital has finally been reached. It feels like I'm done, but there's still a long way to go through Riga. Standing in traffic jams, endless road works, mess. Another sign that I have arrived in Riga are the potholes, which have not been encountered on the whole long road. Personally, I really don't like driving through Riga, because there is complete chaos, the likes of which I have not encountered elsewhere. That's why I choose Liepāja over Riga, because there is a much calmer atmosphere, it seems more homely, more familiar there. However, education must be obtained and Riga has the best universities in Latvia, so there is really nothing left to do but to endure it all.",
        tramvajsText: "Every day I need to get from my place of residence in Riga to the University of Latvia, which is located in the very center. Since it is not very convenient and convenient to travel with your own car, the second choice is public transport. The most convenient public transport for me is the tram, because the boarding stop is close enough to my place of residence and it is possible to get to the very center of Riga with one transport. One of the biggest advantages of the tram is that you don't have to stand in long, long traffic jams.",
        tramvajsText2: "And since this transport is part of my way to the University of Latvia, in this illustration I have depicted a tram in the colors of the Riga tram. In addition, the illustration includes a character - a student, which is meant to be me. This character is standing and waiting for the tram to arrive to get to the University of Latvia. And I also am waiting for the tram to get to the city center every day.",
        libraryText1: "On the way to the University of Latvia there is another object that is very important on the common way to the University of Latvia - the National Library of Latvia. I drive past it almost every day, and I always associate this place with learning and knowledge. The library building itself is interesting with its architecture and stands out a little from the rest of Riga's landscape.",
        libraryText2: "The library offers not only a rich collection of books, but also a variety of resources that support learning. I even visit the library myself from time to time to immerse myself in silence and focus on my studies. This is especially convenient for me because public transportation stops right outside the library, allowing me to easily get from there to city centre and back.",
        libraryText3: "Thus, the National Library of Latvia is not only an important symbol and support for studies for me, but also a practical and convenient place that is very close to my road route.",
        uniText: "This long road from Liepāja to the University of Latvia includes a lot of different places that are associated with something. On this path, my destination is the University of Latvia and I have reached it. During the first two years of my studies, I did not really get to make this journey and visit the building of the University of Latvia, because distance studies were set. With the resumption of face-to-face studies, you get to drive, see and visit much more. Over time, I have noticed that the university building does not change externally, it has retained its strong and venerable appearance, which embodies the heritage of tradition and knowledge. It is like a historical building that stands proud and strong, continuing to serve as a temple of knowledge for the new generations. That's why I thought of creating an illustration with the University of Latvia and my image, who got there after all this way.",
        uniText2: "There is still a year left to learn, another year in which I will measure the already measured path several times, I will see all these places and objects. Just as the road is long, this study process also seems very long to me, maybe because I don't feel like I'm at home.",
    }
}